spring:

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    database: mysql
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      platform: sql
      mode: always
      data-locations: classpath:data/data.sql


  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: ${CONTAINER_PORT:8080}

app:
  secret-key: ${SECRET_KEY}

upload:
  dir: uploads